### ISSUE TITLE
bmrcli - CLI tool for heating controller config dump/load

### ISSUE THREAD

**Issue by dankeder** [slesinger/pybmr#3]
Hey,

I'm sharing a CLI tool for dumping/loading the heating controller config:  https://github.com/dankeder/bmrcli

I use it to backup the config in case I screwed something up. If you think it's useful you may mention it in the README somewhere (either here or in the HA-BMR plugin).

**Comment by slesinger** [comment]
Thank you Dan. I have added a reference in this read me.
